### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by yuricorrea** [gilbarbara/react-spotify-web-playback#1]
Hi!
There's the "add to queue" functionality? I'm trying to use dynamic uris but the player always back to first song when I add a new uri
Ex: `uris={this.state.uris}`

**Comment by gilbarbara** [comment]
Hey!

You'll need to set the `offset` prop, which is the desired index from the `uris` you want to play and you can add tracks to the `uris` and keep the same `offset`.
Does it work for you?

**Comment by gilbarbara** [comment]
You can check this functionality at https://musicbot.io

**Comment by yuricorrea** [comment]
@gilbarbara I added offset, but when I add uri to state it returns to the beginning of current song

**Comment by gilbarbara** [comment]
Make sure that `uris` is an array of Spotify's URIs.
Note that `offset` is zero-based, so if you want to play the third track set it to 2

```js
<SpotifyPlayer
	uris={[
		'spotify:track:2x5Frs6ts14U4MSLrQQlXg',
		'spotify:track:62dXSB964Zgcz2Hq5sjoJd',
		'spotify:track:7d3FO1jCqAspJbPWVnoUle',
		'spotify:track:6nsLsKvV7Bzgh0SMLXCiI0',
	]}
	offset={2}
/>

```

**Comment by yuricorrea** [comment]
@gilbarbara  I know
I've made a fix for this.

With this code I add one new uri just when offset is change, so the player comes back from the beginning, but it was already at the beginning anyway

```
getSpotifyUris(){
        const { tracks, offset } = this.state;
        return tracks.slice(0,offset + 2).map( track => {
            return track.source.uri
        });
    }
```

```
<SpotifyPlayer
        token={this.state.token}
	uris={this.getSpotifyUris()}
	offset={this.state.offset}
/>
```
