### ISSUE TITLE
When the "uris" property receives a variable array does not work

### ISSUE THREAD

**Issue by igornj** [gilbarbara/react-spotify-web-playback#100]
**The Bug**
I'm sending to the "uris" property an array with some uris inside the play the musics as a playlist. But instead of playing I get this error on the request:
**{status: 403, message: "Player command failed: Restriction violated", reason: "UNKNOWN"}**

The strange part is that when I grab the same values from this variable array and put it straight in the property, it works.

**On next print screens, its the error occurring when I use a variable array:**
![image](https://user-images.githubusercontent.com/78692995/157515022-ebde72a8-fba0-40a4-b59f-aed93d888c00.png)
![image](https://user-images.githubusercontent.com/78692995/157515327-0e1509c9-f9c9-40b4-a1d7-9498636b96e1.png)
![image](https://user-images.githubusercontent.com/78692995/157514736-4ec516c6-2c09-4907-a750-77f89b9ade9d.png)

**On this next ones, its me using the same values inside the array above, but putting straight to the uris property, and it works fine:**
![image](https://user-images.githubusercontent.com/78692995/157517361-892a2301-f72c-4c19-9b8d-eb5fca30deeb.png)
![image](https://user-images.githubusercontent.com/78692995/157517322-92934af7-bad6-4919-beb7-fb1b51d097a5.png)

**To Reproduce**
1. Go to my [github repo](https://github.com/igornj/animefy) and download the project
2. Start both the server and client folder
3. Go to the components on the client folder and then open the Player.tsx file
4. Login with your spotify on browser on the localhost:3000/login
5. Search for a music and click on it
6. It'll play cause its using a single "uri"
7. Now apply the methods showed above on the prints to achieve the errors

**Expected behavior**
Either the error 403, or play the playlist with the value put it into straight

**Desktop:**
 - Windows
 - Browser Opera, Chrome

**Additional context**
I just want it to play the uris inside the variable array

**Comment by gilbarbara** [comment]
Hey @igornj 

I've tried to run the app but nothing worked...

Anyway, this library is a wrapper for the Spotify Web Playback SDK and I can't debug errors with their API.
You can try to replay the same request in Postman or another client to understand what's happening.
Make sure to check that you can play the track/playlist since some objects are geo-restricted.
The error is cryptic but definitely is a restriction on their side.

[s]

**Comment by igornj** [comment]
Thanks for your time,

Yeah, I don't know exactly why it works when its not a variable array in there. I'm just gonna change the feature and move on from now.

thank you
