### ISSUE TITLE
Cannot read properties of undefined (reading 'Player')

### ISSUE THREAD

**Issue by timidri** [gilbarbara/react-spotify-web-playback#104]
**Describe the bug**
When using the SpotifyPlayer, during first time rendering, the error is displayed (Chrome):  
```
TypeError
Cannot read properties of undefined (reading 'Player')
```

In Safari, the following error is displayed:
```
TypeError
undefined is not an object (evaluating 'new window.Spotify.Player')
```

**To Reproduce**
1. Go to 'https://codesandbox.io/s/fervent-tree-94wc2j?file=/src/App.js'
2. See error
3. If needed, replace the const TOKEN by a valid Spotify token

**Expected behavior**
The SpotifyPlayer renders properly the first time.

**Codesandbox link (Required)**
Include a codesandbox will help us to investigate the issue quicker.

[CodeSandBox](https://codesandbox.io/s/fervent-tree-94wc2j?file=/src/App.js)

**Screenshots**
Error on Safari:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/1586813/173164896-d095baed-5d90-4675-9a6b-97a086d946c2.png">

Error on Chrome: 
<img width="541" alt="image" src="https://user-images.githubusercontent.com/1586813/173164904-da941db8-1cde-470c-b829-29bb08f5493e.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.3.1 (21E258)
 - Browser Safari Version 15.4 (17613.1.17.1.13) or Chrome Version 102.0.5005.61 (Official Build) (x86_64)

**Comment by gilbarbara** [comment]
This is probably related to React's StrictMode. 
Not sure this package would work with it since it inject the player directly into the host app.

**Comment by timidri** [comment]
Without StrictMode it does indeed seem to work better, although it still doesn't render properly the first time.
However, even with StrictMode, it does render properly the second time and keeps working after that. Are you sure it isn't a timing issue?

**Comment by gilbarbara** [comment]
What do you mean with "it still doesn't render properly the first time"? Even with a proper token?

**Comment by timidri** [comment]
The first render looks like this now: 
<img width="556" alt="image" src="https://user-images.githubusercontent.com/1586813/173191386-599033c3-06c7-4253-b158-c3506f2d1b74.png">

After pressing "play" it renders like so:
<img width="543" alt="image" src="https://user-images.githubusercontent.com/1586813/173191402-83b374c9-d548-4d78-8a8e-beeb1d7386e4.png">

**Comment by timidri** [comment]
@gilbarbara I am using next.js with SpotifyPlayer and I have the same behaviour. If I disable StrictMode, the player does render the first time, but is non-functional (and doesn't display the track title nor icon, although the trackUri is set and autoPlay is on). I need to explicitly press Play after which the player is rendered correctly, starts playing, and restarts playing after 2 seconds, after which it continues to play,

**Comment by gilbarbara** [comment]
hey @timidri 
The player doesn't load the track data before it starts playing, this is the expected behavior.

I've never tried to run this library with SSR but autoPlay probably won't work...

I've tried to debug this play state change and it only happens sometimes, so it might be a bug on the WebPlayback SDK.
The library waits for the player to be loaded and "ready" before trying to play anything.

**Comment by timidri** [comment]
@gilbarbara Good point about SSR. I've disabled SSR for the player component and it's indeed more stable (the stage change whereby the play starts again doesn't seem to happen). However, autoplay still doesn't seem to work.
What's strange is that in this youtube video: https://www.youtube.com/watch?v=5qwpAn8bqCg next.js is also used and SpotifyPlayer does seem to do autoplay without changing the default behaviour.

**Comment by gilbarbara** [comment]
hey @timidri 

I tried to check the video but it's too long and I couldn't catch the page load with autoPlay. However, if it's working there, it might be the implementation.

You could set the `autoPlay` to true when the parent component mounts (client-side) and use a `key` in the player so it will rerender.
Something like [this](https://github.com/gilbarbara/react-spotify-web-playback/blob/main/demo/src/App.tsx#L183).

**Comment by timidri** [comment]
@gilbarbara thanks, I will have a good look at the example you linked. And sorry, I should have given you a timestamp of the video, here: https://youtu.be/5qwpAn8bqCg?t=20902 is the beginning of the coding of the SpotifyPlayer component.

**Comment by gilbarbara** [comment]
@timidri 

From what I could understand, he's using a `useEffect` to only show the player when the app is rendered on the client-side, so that's why autoPlay is working.

Good luck!

**Comment by gilbarbara** [comment]
Fixed StrictMode with React 18.x in v0.10.0

Thanks
