### ISSUE TITLE
TypeError: (0 , memoize_one_1.default) is not a function

### ISSUE THREAD

**Issue by mellie192** [gilbarbara/react-spotify-web-playback#107]
**Describe the bug**
When trying to render the player, I get the following error:
TypeError: (0 , memoize_one_1.default) is not a function

**To Reproduce**
1. Create a new NextJS project
2. Import the player in pages/index.js

My specs:
 - OS: Windows 11
 - Browser: Firefox & Chrome
 - React version: 18.2.0
 - NextJS version: 12.1.6
 - react-spotify-web-playback: 0.10.0
 - Node Version: 14.19.1

**Comment by gilbarbara** [comment]
hey @mellie192 

This library is a wrapper for the Spotify Web Playback SDK that only works in the browser, so it doesn't support SSR.
So you'll need to render it AFTER the component is mounted in the client.

Anyway, as stated in the issue template, issues without a codesandbox example will likely be ignored.
