### ISSUE TITLE
Possible to control the next and previous button ?

### ISSUE THREAD

**Issue by Nicolas-Noseda** [gilbarbara/react-spotify-web-playback#116]
Hello, is it possible to control the next and previous button to change the music via code ?

**Comment by gilbarbara** [comment]
Hey @Nicolas-Noseda 

Not exactly. You can change the `offset` prop.

**Comment by Nicolas-Noseda** [comment]
For those who need to change the music i made it with this for next song : document.querySelector('button[title="Next"]').click();
And this for previous : document.querySelector('button[title="Previous"]').click();
