### ISSUE TITLE
Module not found: Error: Can't resolve 'nano-css/addon/jsx'

### ISSUE THREAD

**Issue by inkxk** [gilbarbara/react-spotify-web-playback#127]
<img width="804" alt="Screenshot 2566-01-17 at 22 02 06" src="https://user-images.githubusercontent.com/64063112/212933415-760ca504-16c3-404f-b6b1-7c66603bdab7.png">

I have installed nano-css but it doesn't work.

<img width="435" alt="Screenshot 2566-01-17 at 22 04 56" src="https://user-images.githubusercontent.com/64063112/212934300-d16e43d8-3227-4c42-98eb-5f285915deae.png">

**Comment by gilbarbara** [comment]
Hey @inkxk 
Please use the 0.10.1 version for now.

**Comment by gilbarbara** [comment]
@inkxk 
Fixed in 0.11.2
