### ISSUE TITLE
Swapping the access token causes two songs to play at once when changing the song

### ISSUE THREAD

**Issue by Nickprovs** [gilbarbara/react-spotify-web-playback#13]
1.) Start a song.
2.) Request a new access token via refresh token. Update the state (access token).
3.) Skip to the next song or request play to a new uri.
4.) You'll start hearing both songs at once.

**Comment by gilbarbara** [comment]
Needs example

**Comment by Nickprovs** [comment]
> Needs example

My current project has a little too much going on so I'll write a little test app before 01/27.

**Comment by Nickprovs** [comment]
A bit late... but here's a quick example.

https://github.com/Nickprovs/token-issue

There's a README in the root to get it up in running. The example boils down to this...

The client app requests a new token every 15 seconds. You'll notice in the client console that it's getting a new one. This token is passed to the player control via props. There will be a button on the player page to play a random song from a playlist.

Hit it once. It'll start playing. All good.

Hit it again once you have  a new token. And you'll start hearing double.

Let me know if you have any questions. It's possible I'm doing something totally egregious but I'm not sure.

Best,

Nick

**Comment by raj793** [comment]
Having the same issue.

**Comment by raj793** [comment]
I found a workaround for this (You lose the player controls after token refresh though, but if you're just looking for continuous playback then this should do)

const timerHandle = useRef(null)

const requestToken = async () => {
    try {
      let res = await axios.post('https://accounts.spotify.com/api/token', querystring.stringify(requestBody), config)
      if (res.status !== 200 || !res.data) {
      } else {
        setSpotifyToken(res.data.access_token)
      }
    } catch (err) {
    }
  }

  const startPlaybackSession = () => {
    requestToken()
    timerHandle.current = setInterval(() => { requestToken() }, 3600000)
  }

**Comment by gilbarbara** [comment]
Hey,

@raj793 I've seen the token expire before the 1 hour period, so I think it's better to listen to authentication errors in the callback and if there's an invalid token error you can get a new one and update the player.

This way the request isn't made during songs and avoid the intterruption

**Comment by gilbarbara** [comment]
Also, try to set the token as the `key` prop in the Player if you encounter the player duplicate or have any weird artifacts.

**Comment by raj793** [comment]
> Hey,
> 
> @raj793 I've seen the token expire before the 1 hour period, so I think it's better to listen to authentication errors in the callback and if there's an invalid token error you can get a new one and update the player.
> 
> This way the request isn't made during songs and avoid the intterruption

Is there any chance of audio continuity breaking if the player is already playing audio?

**Comment by gilbarbara** [comment]
As I said, the request isn't made during play, just when it needs to load a song

**Comment by raj793** [comment]
> As I said, the request isn't made during play, just when it needs to load a song

During my tests, song would stop playing as soon as token would expire in an hour.
