### ISSUE TITLE
Cannot import SpotifyPlayer from 'react-spotify-web-playback'

### ISSUE THREAD

**Issue by KacperKubic** [gilbarbara/react-spotify-web-playback#130]
I cannot import SpotifyPlayer from 'react-spotify-web-playback' there is no such export in this package. <br/>
When I do it and use it there are 6 errors in the consoles. **All of them looks the same but are meant for different files**. Here is the error: <br/>
"ERROR in ./node_modules/react-spotify-web-playback/dist/index.mjs 78:0-55
Module not found: Error: Can't resolve 'nano-css/addon/jsx' in 'D:\react\spotify-clone\node_modules\react-spotify-web-playback\dist'
Did you mean 'jsx.js'?
BREAKING CHANGE: The request 'nano-css/addon/jsx' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request." 
In every of the errors the only part that is different is "Did you mean '...'?"
<br/>
<b>Complete list of files in the "did you mean" part:</b>
- Did you mean 'jsx.js'?
- Did you mean 'keyframes.js'?
- Did you mean 'nesting.js'?
- Did you mean 'rule.js'?
- Did you mean 'style.js'?
- Did you mean 'styled.js'?

<b>I tried to add "type:module" to package.json but it gave me different errors and problems related to the react-spotify-web-playback </b> <br/>
1. Go to console and type npm install react-spotify-web-playback
2. Try to import SpotifyPlayer from 'react-spotify-web-playback'
3. See error

![image](https://user-images.githubusercontent.com/110545146/215355109-1262cdc5-05f1-4476-ba3d-2ca95064a017.png)

**Comment by gilbarbara** [comment]
Hey @KacperKubic 

Which version are you using?
Issues without a codesandbox are liked to stall, as mentioned in the issue template for this repo.

Can you load the demo in [codesandbox](https://codesandbox.io/s/github/gilbarbara/react-spotify-web-playback/main/demo)? If it's working, then it must be a problem with your setup. Update to the last version and try again.

**Comment by gilbarbara** [comment]
If you are using next.js, you'll need to load the player dynamically since it doesn't work with SSR.
Check the [docs](https://nextjs.org/docs/advanced-features/dynamic-import) for examples.

**Comment by KacperKubic** [comment]
I tried to recreate the issue in codesandbox but everything works fine here.
I am using plain React.js (without next.js) and I installed version 0.11.1 of react-spotify-web-playback so to my knowlage this is the newest one. 
Do you have any ideas what can be a problem? I even created new clear react project on my PC and installed only this package and it gave me the same error. 

Here is my code on codesanbox:
https://codesandbox.io/s/admiring-dubinsky-wpxid5?file=/src/App.js

**Comment by KacperKubic** [comment]
I installed the previous version (0.10.0) and everything works now. I will just stick to this version

**Comment by gilbarbara** [comment]
@KacperKubic 
There are some bugs in v0.10, but glad it worked for you.

But I still want to debug the problem and try to fix it.
Can you describe your setup? How are you bundling your app?
Did you use create-react-app, vite, or another build tool in your project?

**Comment by gilbarbara** [comment]
@KacperKubic 

Fixed in v0.11.2
Let me know if it works for you.

**Comment by KacperKubic** [comment]
Sorry for not responding for so long. Everything works now with version 0.11.2. Thank you for you very fast help!
