### ISSUE TITLE
canUseDOM error

### ISSUE THREAD

**Issue by AnmaritoS** [gilbarbara/react-spotify-web-playback#144]
### Describe the bug

Whenever i try to deploy to vercel, it gives me an error in the react-spotify-web-playback/dist/index.mjs:64.
Here's the error : 

import { canUseDOM as canUseDOMBool } from "exenv";
--
21:29:24.059 | ^^^^^^^^^
21:29:24.059 | SyntaxError: Named export 'canUseDOM' not found. The requested module 'exenv' is a CommonJS module, which may not support all module.exports as named exports.
21:29:24.059 | CommonJS modules can always be imported via the default export, for example using:
21:29:24.060 |  
21:29:24.060 | import pkg from 'exenv';
21:29:24.060 | const { canUseDOM: canUseDOMBool } = pkg;
21:29:24.060 |  
21:29:24.060 | at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
21:29:24.060 | at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
21:29:24.061 |  
21:29:24.061 | > Build error occurred
21:29:24.064 | Error: Failed to collect page data for /
21:29:24.065 | at /vercel/path0/node_modules/next/dist/build/utils.js:991:15 {
21:29:24.066 | type: 'Error'
21:29:24.066 | }
21:29:24.133 | Error: Command "npm run build" exited with 1
21:29:24.873 | BUILD_FAILED: Command "npm run build" exited with 1

</body>
</html>
9:39:24 PM: const { canUseDOM: canUseDOMBool } = pkg;
9:39:24 PM:     at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
9:39:24 PM:     at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
9:39:24 PM:     at async Promise.all (index 0)
9:39:24 PM:     at async ESMLoader.import (node:internal/modules/esm/loader:530:24)
9:39:24 PM:     at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
9:39:24 PM: > Build error occurred
9:39:24 PM: Error: Failed to collect page data for /
9:39:24 PM:     at /opt/build/repo/node_modules/next/dist/build/utils.js:991:15 {
9:39:24 PM:   type: 'Error'
9:39:24 PM: }

### Your minimal, reproducible example

https://github.com/AnmaritoS/Spotify-Redesign

### Steps to reproduce

You should first install all the packages i have in the package.json and then you should be able to npm run build

### Expected behavior

Im expecting my application to deploy

### How often does this bug happen?

Every time

### Screenshots or Videos

![Capture](https://user-images.githubusercontent.com/95002766/223903633-b8036d4a-acc7-4b8a-a127-4d31985956cc.PNG)

### Platform

windows 10
google chrome

### react-spotify-web-playback version

0.13.1

### Build tool

next.js

**Comment by gilbarbara** [comment]
Check the comment in this [discussion](https://github.com/gilbarbara/react-spotify-web-playback/discussions/143).
