### ISSUE TITLE
Typescript error between URIs and syncExternalDevice

### ISSUE THREAD

**Issue by cravend** [gilbarbara/react-spotify-web-playback#154]
### Describe the bug

The URIs is currently a required prop. However, I believe that if I'm using `syncExternalDevice`, I don't need to pass the URIs in at all. 

### Your minimal, reproducible example

https://codesandbox.io/s/relaxed-chihiro-6xpyk8

### Steps to reproduce

n/a

### Expected behavior

I should be able to sync with my external device and not manually start playing a particular song.

### How often does this bug happen?

Every time

### Screenshots or Videos

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/7117993/229375646-cbe4b68d-7e36-4a47-97d5-da398baffb9e.png">

### Platform

- macOS

### react-spotify-web-playback version

v0.13.4

### TypeScript version

v4.9.5

### Build tool

next.js

### Additional context

I believe this is just a Typescript error — if I don't pass in the URIs and use @ts-expect-error, it works as expected. I am willing to make a PR for this issue!

**Comment by gilbarbara** [comment]
> If there are no URIs and an external device is playing, use the external player context.

No URIs, in this case, is an empty array.
