### ISSUE TITLE
Cannot read properties of undefined (reading 'reduce')

### ISSUE THREAD

**Issue by mathiaslac** [gilbarbara/react-spotify-web-playback#155]
### Describe the bug

Got this error : 
Cannot read properties of undefined (reading 'reduce')
TypeError: Cannot read properties of undefined (reading 'reduce')

### Your minimal, reproducible example

Both CodeSandbox and my own web app

### Steps to reproduce

1. I've entered the Token (I'm premium)
2. got the error

### Expected behavior

as user, I expected seeing the webplayer but got error

### How often does this bug happen?

Every time

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/46488156/232259757-a3d0e6e9-a1fe-4301-b862-e346c78f37a8.png)

### Platform

- Browser Chrome

### react-spotify-web-playback version

v0.13.4

### Build tool

create-react-app

**Comment by wlhmmxrtz** [comment]
Same issue here, website seems to get suddenly blank.

Before:
![image](https://user-images.githubusercontent.com/94683002/232748610-87800e46-58ee-434f-baf6-6a2693b76f1b.png)

After entering the access token:
![image](https://user-images.githubusercontent.com/94683002/232748999-b4fadc1c-fa83-446e-b151-7de736c3ddfd.png)
![image](https://user-images.githubusercontent.com/94683002/232749273-38e04685-d17d-446d-b8a4-c0285957fc5d.png)

Please note thatI'm a beginner in react and not very experienced in coding so it would be great to know when and if the bug has been fixed.

**Comment by gilbarbara** [comment]
Hey @wlhmmxrtz 
Your token isn't valid (the 401 error), which might also trigger some other errors.

You can use an ErrorBoundary to prevent the white screen.

**Comment by mathiaslac** [comment]
@gilbarbara I tried again just now, on your demo page and it gives me this error... :
``
{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}
```

**Comment by gilbarbara** [comment]
@mathiaslac 
Spotify changed their docs and stopped showing the token with the correct permissions on their page.
I've updated the demo to redirect to a page with the proper token. Please try again.

Also, I have a fix for the Devices components not to break if it can't get the devices that I'll publish soon.

**Comment by mathiaslac** [comment]
@gilbarbara 
I feel the same way :(
```
{
  "error": {
    "status": 401,
    "message": "No token provided"
  }
}
```
![image](https://user-images.githubusercontent.com/46488156/233505377-195c9875-1d48-4d31-80b9-2a99302fbfd7.png)

**Comment by gilbarbara** [comment]
@mathiaslac 
The image implies that you're getting 403 errors, not 401.
403 means your token isn't allowed to perform the operation.

Are you using your own token or copying it from a page that looks like this?
<img width="735" alt="CleanShot 2023-04-20 at 20 33 57@2x" src="https://user-images.githubusercontent.com/31954/233507956-87c0546b-5668-44d6-a378-5f8c473008b8.png">

**Comment by mathiaslac** [comment]
@gilbarbara  
Yes I'm using this token given from this page

**Comment by gilbarbara** [comment]
Fixed in v0.14

**Comment by mathiaslac** [comment]
retried using your demo page, my account is premium but got 
![image](https://user-images.githubusercontent.com/46488156/235344393-978dd241-61bc-457c-bb8c-38ee8f02d740.png)

**Comment by gilbarbara** [comment]
Hey @mathiaslac 

The Spotify app used in the demo is not approved by Spotify yet, so you might get some errors.
Generate a user token on your own and try it. The token needs to start with `BQ`

**Comment by Johnnywrightiv** [comment]
I'm having the same issue with the 403 on the demo page. My account is premium and I'm using the token from the given page with the green background pictured above. Is there a way to generate my own user token to test and does it have to do with the dev clientID? Sorry I'm still fairly new to authentication and tokens.

**Comment by gilbarbara** [comment]
Hey @Johnnywrightiv 

Yeah, the direct token flow is broken for now.
You'll definitely need your own token to use the player in an app.
Check out the Spotify [docs](https://developer.spotify.com/documentation/web-api/concepts/authorization)
You'll need to use a flow that provides a token to access user resources, such as an Authorization code.
