### ISSUE TITLE
Cannot pass new offset to Spotify Player Component with same album URI

### ISSUE THREAD

**Issue by ZacharySal** [gilbarbara/react-spotify-web-playback#166]
### Describe the bug

Whenever an album uri is passed to the player component, future changes to the offset prop result in an invalid fetch request to the Spotify API and the track does not change, it continues playing the same track. When the uri and offset are initially changed and passed to the player component, everything works correctly and the request to the Spotify API is **correct** with this body structure 
`{ offset: {position: 5}, context_uri: albumURI }`

However, if the user tries to select a new track in the same album, the offset changes and the offset passed to the play component also changes. The uri does not change. However, the request to the Spotify API is **incorrect** with this body structure 
`{ offset: {position: 8}, uris:[albumURI] }`

It does not mark the uri as a context_uri and thus the Spotify API returns an error with status code `400` and message
`"position out of range"`

### Your minimal, reproducible example

https://codesandbox.io/p/sandbox/nkmfxs

### Steps to reproduce

1) Add your user access token in the sandbox 
2) Click the play button next to one of the tracks, the track will begin playing in the player
3) Try clicking play next to one of the other songs, you will notice the selected offset changes, but not the track
4) Check the network requests in dev tools to view the failed request 

### Expected behavior

I expected the selected track, with the updated offset, to begin playing. 

### How often does this bug happen?

Every time

### Screenshots or Videos

https://github.com/gilbarbara/react-spotify-web-playback/assets/60337802/6ed85983-59cf-4a45-9f00-18fe3ba21ff5

### react-spotify-web-playback version

0.14.1

**Comment by gilbarbara** [comment]
Great, having a sandbox really helps. Rumours ❤️
I'll take a look today.

**Comment by gilbarbara** [comment]
Alright, fixed in 0.14.2

The `toggleOffset` function was passing `uris` instead of `context_uri`, one-liner fix! :)

**Comment by ZacharySal** [comment]
Awesome. Thank you for the quick fix!
