### ISSUE TITLE
Access token not working in demo

### ISSUE THREAD

**Issue by Utsavjain4561** [gilbarbara/react-spotify-web-playback#17]
I am not a Spotify premium user . Does this mean i cannot use this API ? as token generated from my account failed authentication in your demo

**Comment by gilbarbara** [comment]
Yes, it's on the [Web Playback SDK](https://developer.spotify.com/documentation/web-playback-sdk/) documentation that is linked in the README.

**Comment by Utsavjain4561** [comment]
Thanks for the comment , but can you suggest me how could I possibly play a spotify song in my application ?

**Comment by gilbarbara** [comment]
Without a premium subscription, you can just play the 15s preview.
