### ISSUE TITLE
Component does not accept track uri's

### ISSUE THREAD

**Issue by Huynheddie** [gilbarbara/react-spotify-web-playback#18]
I've been trying to pass in a specific track's uri ("spotify:track:1gahyBwl7jWJ91m052fgxU" for example) and I keep getting a "400 Non supported context uri" error. In the headers, I can see that the component is passing in the uri as the "context_uri" key rather than "uri", which does not support playing specific tracks. Is there any way around this?

**Comment by gilbarbara** [comment]
Hey,

Did you check the demo? https://codesandbox.io/s/react-spotify-web-playback-demo-dye1g
I've just tried and it is working with tracks too.

**Comment by Huynheddie** [comment]
Yeah, when I try to pass in that spotify track I provided in the earlier comment nothing seems to be happening. I can play the 'Play some Tracks' song fine, but putting a different track URI in doesn't seem to work.

**Comment by Huynheddie** [comment]
Ah I figured it out, it looks like you need more than one track uri in order to play them! Thanks for the help.

**Comment by gilbarbara** [comment]
@Huynheddie this behavior will change in 0.7.0
