### ISSUE TITLE
NPE in demo

### ISSUE THREAD

**Issue by kevinwaterloo** [gilbarbara/react-spotify-web-playback#22]
I was testing out the demo and I get a `Cannot read property 'length' of undefined' in Devices.js after inputting my access token. 

![image](https://user-images.githubusercontent.com/8786317/87865135-62724500-c93f-11ea-8384-0b3e773c2869.png)

Also running into this issue when using the React component.

Thanks!

**Comment by gilbarbara** [comment]
Hey @kevinwaterloo 

It's impossible to know what is happening on your machine. What is NPE, anyway?

What is the 401 error you are having with the Spotify API?
Are you using a valid Spotify Premium subscription?

Check the [Spotify Web Playback SDK](https://developer.spotify.com/documentation/web-playback-sdk/) for more details of the requirements.

**Comment by pritammobisoft** [comment]
@gilbarbara >> Are you using a valid Spotify Premium subscription?

Does this apply to the users of the app also? Or the premium account is required for the developers only?

Thanks!

**Comment by gilbarbara** [comment]
@pritammobisoft 
Yes, is in the documentation: https://developer.spotify.com/documentation/web-playback-sdk/#requirements

**Comment by pritammobisoft** [comment]
@gilbarbara Thanks a lot for the quick reply! Much appreciated!
