### ISSUE TITLE
issue retrieving track bc of scope?

### ISSUE THREAD

**Issue by anthonychoi98** [gilbarbara/react-spotify-web-playback#25]
spotify recently removed their user-read-birthdate scope and so we can't get a token with that scope, which may be the reason why https://api.spotify.com/v1/me/player/play?device_id={...} is resulting in a 403 error

**Comment by gilbarbara** [comment]
Hey,

Spotify deprecates that scope, but the player is working normally as you can see in the demo.
Are you using a Premium account?

**Comment by anthonychoi98** [comment]
Yes, I am!

**Comment by Carson-Tang** [comment]
Hey, I appear to be getting the same issue with just tracks (albums work as intended), this might be worth taking a closer look at?

**Comment by gilbarbara** [comment]
@Carson-Tang @anthonychoi98 
Please post the tracks you are having problems or even better create a codesandbox.

Without it, it's impossible to know what is going on...

**Comment by gilbarbara** [comment]
Is the demo working for you? https://react-spotify-web-playback.gilbarbara.dev/

**Comment by Carson-Tang** [comment]
I believe it's all tracks? But I've only tested it on `spotify:track:3UEnF6y5tyHVtMzldS3svp` (https://open.spotify.com/track/3UEnF6y5tyHVtMzldS3svp?si=frOnk5KjTtC8_goDARGf3w), `spotify:track:0a0FISfY8ty1xC69xCWf2T` (https://open.spotify.com/track/0a0FISfY8ty1xC69xCWf2T?si=GLF5QkjpRAikM3_M6eUKqg).

Playing the URI for an artist works fine, tested on `spotify:artist:23fqKkggKUBHNkbKtXEls4` (https://open.spotify.com/artist/23fqKkggKUBHNkbKtXEls4?si=nBNy_RUnQj-pRevEgBwYaQ).

Also, as an aside, how does the demo request the scope for birthdate if the `user-read-birthdate` scope is deprecated?

![image](https://user-images.githubusercontent.com/31937503/89806026-8242f600-db04-11ea-8121-b32874ba42d7.png)

(although it probably wouldn't fix the issue I'm having with the tracks)

**Comment by sjaugmented** [comment]
I'm having the same issue with scope and authorization. Using a premium account, the demo isn't working for me and I can't get the player to authorize in my app either.

**Comment by isaacaddis** [comment]
same here. the problem seems to be with the user-read-birthdate scope

**Comment by isaacaddis** [comment]
The demo seems to work with my auth tokens I gen in my project (using all the scopes except for user-read-birthdate), but I get a 403 whenever I try to actually play something in my project

**Comment by gilbarbara** [comment]
hey @isaacaddis 

> Edit: I think using SpotifyWebPlayer and not SpotifyPlayer (the README provides an example using SpotifyPlayer) just fixed it for me. Great tool by the way! Thanks

I didn't understand your comment. Do you mean the name given to the imported component?

**Comment by gilbarbara** [comment]
Please check version 0.7.0
