### ISSUE TITLE
Example snippet doesn't appear to work (Restriction violated)

### ISSUE THREAD

**Issue by Justice4Joffrey** [gilbarbara/react-spotify-web-playback#26]
Cool looking tool - thanks foor putting this together. Having an issue creating the bare example, however.

Authentication seems to work fine, requests are all 200s etc. so token is OK. 

```
import SpotifyPlayer from "react-spotify-web-playback";
<SpotifyPlayer
    token={mySpotifyToken}
    uris={["spotify:artist:6HQYnRM4OzToCYPpVBInuU"]}
/>
```

Clicking 'play' results in a failed request which sends a request of Content-Length 0 to the play endpoint (e.g. the valid requests in your demo apps send a request payload with uris, context_uri etc.). Feels something along the lines of not picking up the uris data provided.

This request returns -

```
{
  "error" : {
    "status" : 403,
    "message" : "Player command failed: Restriction violated",
    "reason" : "UNKNOWN"
  }
}
```

Perhaps I'm missing something?

Might be useful if you could give a link to your demo apps source.

**Comment by gilbarbara** [comment]
Hey

Please refer to https://github.com/gilbarbara/react-spotify-web-playback/issues/2#issuecomment-522026739

Apart from that, I can't help with Spotify API errors
