### ISSUE TITLE
Passing volume as a prop?

### ISSUE THREAD

**Issue by j0hnk1m** [gilbarbara/react-spotify-web-playback#28]
As the title suggests, is there any way to pass a volume (decimal between 0 and 1) as a prop to the SpotifyPlayer component?

**Comment by gilbarbara** [comment]
hey @j0hnk1m 

not really but how it would work?
Just an initial value or fully controlled hiding the volume component from the UI?

**Comment by j0hnk1m** [comment]
Thanks for the reply @gilbarbara !
Both would be amazing to have: currently, the default volume is set to 100%, which is super loud, and even if I lower the volume, it reverts back to 100% after changing a song. It would be also nice we could pass in a variable to control the volume at all times.

**Comment by gilbarbara** [comment]
@j0hnk1m I'll add an `initialVolume` prop in the next release, but full controlled mode isn't something that fits this library philosophy.

Thanks
