### ISSUE TITLE
SpotifyPlayer component keeps showing loading animation

### ISSUE THREAD

**Issue by j0hnk1m** [gilbarbara/react-spotify-web-playback#29]
Sometimes (especially when I render the component on a page, change pages, then come back), the components never actually loads and is stuck in the loading animation until I manually refresh the page. Is anyone else having this issue?

**Comment by gilbarbara** [comment]
hey @j0hnk1m 

Please post a codesandbox example

**Comment by gilbarbara** [comment]
hey @j0hnk1m 

Did you try to set a key to this component so it won't re-render itself unless the key changes?
I'm using it at [musicbot.io](https://musicbot.io) and I'm not having this issue.

**Comment by gilbarbara** [comment]
@j0hnk1m 

I've identified the problem. The SDK was already loaded so it skipped the initialization.
It will be fixed in the next release.
