### ISSUE TITLE
multiple errors in react 

### ISSUE THREAD

**Issue by QuietMonkey** [gilbarbara/react-spotify-web-playback#3]
TypeError: this._getTokenRequests[t.ref] is undefined
index.js:9:8936
    _onToken https://sdk.scdn.co/embedded/index.js:9
    <anonyme> self-hosted:1011
    _handleMessages https://sdk.scdn.co/embedded/index.js:9
    <anonyme> self-hosted:1013
    _receiveMessage https://sdk.scdn.co/embedded/index.js:9
    <anonyme> self-hosted:1009

TypeError: this._streamer is null
3 index.js:9:9029
    _onGetCurrentState https://sdk.scdn.co/embedded/index.js:9
    <anonyme> self-hosted:1011
    _handleMessages https://sdk.scdn.co/embedded/index.js:9
    <anonyme> self-hosted:1013
    _receiveMessage https://sdk.scdn.co/embedded/index.js:9
    <anonyme> self-hosted:1009

The above error occurred in the <Devices> component:
    in Devices (created by Actions)
    in div (created by style(ActionsRSWP))
    in style(ActionsRSWP) (created by Actions)
    in Actions (created by SpotifyWebPlayer)
    in div (created by style(ContentRSWP))
    in style(ContentRSWP) (created by Content)
    in Content (created by SpotifyWebPlayer)
    in div (created by style(PlayerRSWP))
    in style(PlayerRSWP) (created by Player)
    in Player (created by SpotifyWebPlayer)
    in SpotifyWebPlayer (at App.js:190)
    in div (at App.js:157)
    in App (at src/index.js:7)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries. index.js:1375

TypeError: devices is undefined
Devices.js:120
    render Devices.js:120
    React 10
    renderRoot self-hosted:1110
    runRootCallback React
    runRootCallback self-hosted:1110
    flushSyncCallbackQueueImpl React
    unstable_runWithPriority scheduler.development.js:674
    React 6
    updateState index.js:996
    handlePlayerStatus index.js:635
    step index.js:162
    verb index.js:93
    fulfilled index.js:45

TypeError: this._client is null
index.js:9:9666
    _onDisconnect https://sdk.scdn.co/embedded/index.js:9
    <anonyme> self-hosted:1011
    _handleMessages https://sdk.scdn.co/embedded/index.js:9
    <anonyme> self-hosted:1013
    _receiveMessage https://sdk.scdn.co/embedded/index.js:9
    <anonyme> self-hosted:1009

TypeError: devices is undefined

**Comment by gilbarbara** [comment]
which version of React?

**Comment by QuietMonkey** [comment]
The last one : 16.9.0

**Comment by gilbarbara** [comment]
That seems to be an exception from the Spotify's Web Playback SDK and not from this library, that is only a player UI on top of it.

Can you provide an online demo reproducing it? I couldn't reproduce it myself.

**Comment by QuietMonkey** [comment]
I'm working on it right now. I use it as a node module, and right now it play songs, but I need to change the actual player (bottom right) before it does anything.
I can't deploy anything right now but..
Here's my Repo => https://github.com/QuietMonkey/Spotifake

**Comment by gilbarbara** [comment]
Let me know where you have it published, I can't run the project...
