### ISSUE TITLE
Question on Update Saved Status

### ISSUE THREAD

**Issue by Subraiz** [gilbarbara/react-spotify-web-playback#30]
I am just a little confused on how to use the updateSaveStatus prop. I am trying to change the song that is playing by clciccking on a another button and I am not sure how to do so.

**Comment by gilbarbara** [comment]
hey @Subraiz 

I'm not sure I understand what you are trying to do.
Do you want to change the song or get the update status?

To change the song you need to update the `uris` prop with the new song(s).

> updateSavedStatus is only needed if you keep the track saved status in your app.

Do you need that?

**Comment by gilbarbara** [comment]
no response...
