### ISSUE TITLE
Read a track's seek time in milliseconds

### ISSUE THREAD

**Issue by prestondunton** [gilbarbara/react-spotify-web-playback#31]
Hi there!  Thank you so much for making this!

I would like to read how far along the track the player is at any given time in milliseconds.  My goal is to trigger text / color changes in an element when the chords change in a track the user is playing (given the millisecond marks of chord changes in a JSON).  

I would also like to be able to seek with arrow keys.  In another part of my application this would help the user enter in chords at certain times in the song without having to click and drag the slider.

Are either of these operations supported?  If not, I would consider adding them myself, though I'm a younger developer and would like some kind of a pointer to where I would start.  Thanks for reading.

**Comment by gilbarbara** [comment]
hey @prestondunton 

Thanks! 😀 

About syncing the player every millisecond, I don't this is feasible for this package. It would make the UI unusable and definitely wouldn't work with external players with API calls.
I could expose the player instance with a getter prop but no official support.

I'll think about keyboard navigation as this package is a widget to be used within a page with other elements, so it can't steal the keyboard focus for itself. Even Spotify's own web player doesn't have this feature probably for the same reason.

**Comment by prestondunton** [comment]
@gilbarbara Thank you for responding so quickly to this.  I now understand the difference between the Spotify Web Playback SDK and the Spotify Web API.  I agree with you now, I don't think that the SDK supports seeking like that.  What I was looking for was actually [this](https://developer.spotify.com/documentation/web-api/reference/player/seek-to-position-in-currently-playing-track/), which is in the API.  
     As far as keys are concerned, I also understand your reasoning there.  I'll let you make the decision.  In the meantime, I don't think I'm quite blocked with my application, so I'll continue to develop with the resources I have available.  Unless you want it open for some reason, I think closing the issue is ok.  Thank you!

**Comment by gilbarbara** [comment]
@prestondunton 

Actually the SDK supports polling every millisecond but CPU usage went crazy.
You can check [here](https://codesandbox.io/s/spotify-web-playback-polling-h4jqi?file=/src/App.js). Just update the interval to 1.

The API won't allow that kind of behavior, for sure.

The keyboard navigation is my radar so I'll close this since the title is about seek time.
