### ISSUE TITLE
Player doesn't play TRACK uri

### ISSUE THREAD

**Issue by NoorFakhry** [gilbarbara/react-spotify-web-playback#33]
Hi @gilbarbara, First of all I want to thank you about this amazing library, it saved me a lot of time.
I am facing an issue, the player only plays the artist uri, and I want to play a track uri..
Thank You again

**Comment by gilbarbara** [comment]
hey @NoorFakhry 

The demo uses artists, albums, and tracks URIs. Isn't working there?

**Comment by NoorFakhry** [comment]
Yes, it actually works in the demo, but it doesn't work in my app when I pass a track Uri as prop to the component, don't know why !!

**Comment by gilbarbara** [comment]
It's impossible to know what's going on in your app. If it's in the demo it's not a bug in the package.
Good luck
