### ISSUE TITLE
How to display position in track? (seconds)

### ISSUE THREAD

**Issue by Jaja0624** [gilbarbara/react-spotify-web-playback#36]
Sorry if this example already exists. Could not find. 

Cheers

**Comment by gilbarbara** [comment]
hey @Jaja0624 
It's not possible right now.

Feel free to submit a PR.

**Comment by gilbarbara** [comment]
I'm working on updating the UI, so it resembles Spotify's own UI.
Check the #41 issue for a preview.

**Comment by gilbarbara** [comment]
Implemented in 0.12.0 🎉
