### ISSUE TITLE
styling for volume / device popup

### ISSUE THREAD

**Issue by Jaja0624** [gilbarbara/react-spotify-web-playback#38]
Is there any way to move the volume / device popup down? If i put it at the top of the page it will be cut off.

![image](https://user-images.githubusercontent.com/31715149/100216701-71599d00-2ec7-11eb-990a-58b47fe85b5f.png)

Cheers

**Comment by gilbarbara** [comment]
hey @Jaja0624 

Not really since it would cut off the handle in the slider.

**Comment by gilbarbara** [comment]
@Jaja0624 I've added detection for the player position, so it would render the drawer top or bottom based on it.

**Comment by Jaja0624** [comment]
> @Jaja0624 I've added detection for the player position, so it would render the drawer top or bottom based on it.

Is it possible to provide a ETA for next release? Is there any way to get access to the changes early?

**Comment by gilbarbara** [comment]
@Jaja0624

Relax man, this is open source...

anyway, it's already published
