### ISSUE TITLE
Sync player to connect api devices playback state on init

### ISSUE THREAD

**Issue by thiemok** [gilbarbara/react-spotify-web-playback#4]
Given that the player has just been initialized and is not supplied with an array of uri to play. But different device is detected as playing using the spotify connect api.
Would it be possible to have the play auto select the currently playing device and sync to its playback status?

If not that would be a great feature to add.

**Comment by gilbarbara** [comment]
@thiemok 

hey,

I've added a prop for that: `syncExternalDevice`. It will be available in 0.7.0.

Here's the list of changes: https://github.com/gilbarbara/react-spotify-web-playback/pull/20 for this version.
I still have some UIs updates to finish before I publish it but it shouldn't tell take long.

**Comment by gilbarbara** [comment]
Please check version 0.7.0
