### ISSUE TITLE
Is it possible to know when the user seeks (changes song position)?

### ISSUE THREAD

**Issue by Jaja0624** [gilbarbara/react-spotify-web-playback#40]
Cheers

**Comment by gilbarbara** [comment]
hey @Jaja0624 
It's not. What's your reasoning for that?

**Comment by Jaja0624** [comment]
actually im trying to create a timer and if the user seeks i need to get the new position value

**Comment by gilbarbara** [comment]
Ok, I'm adding a `progress_update` callback type for this.

**Comment by Jaja0624** [comment]
That's awesome. Thank you so much for ur work.
