### ISSUE TITLE
create compact 'vertical' display mode

### ISSUE THREAD

**Issue by fbegue** [gilbarbara/react-spotify-web-playback#41]
First off - this is AMAZING thank you so much for providing this for the community!

I'm looking at trying to fit the player into a side panel on my website, so it would look more like this:

![player_preview](https://user-images.githubusercontent.com/8701694/100384859-22a72280-2fef-11eb-8a32-9e4e3251bf6c.png)

From pulling down the repo and perusing, looks like I need to modify the **Info** component and then move it so it's above the **Slider** component in the index.tsx render. I would attempt this myself but thought: 

1) maybe this was already an enhancement that you were thinking about
2) I can't build (_Invalid switch - "*"._ while cleaning? I didn't try super hard diagnose - probably my fault)
3) I am a junior dev and this looks . . like a professional made it. not like my projects :) 

Anyways just wanted to get your input before looking into this anymore.

Thanks again!

**Comment by gilbarbara** [comment]
hey @fbegue 

Thanks! 👍 

Yeah, I'm already working on a UI update and I'll probably add a "compact" layout alongside themes.
Not sure about ETA yet, but soon.

### Compact
![compact](https://user-images.githubusercontent.com/31954/101168448-3b7c8d00-361a-11eb-887a-35b23a7aade1.png)

### Inline (large screens)
![inline-desktop](https://user-images.githubusercontent.com/31954/101168457-3ddee700-361a-11eb-9b51-95e2090349f2.png)

### Inline (mobile)
![inline-mobile](https://user-images.githubusercontent.com/31954/101168459-3ddee700-361a-11eb-8dfc-06737c7859f8.png)

**Comment by fbegue** [comment]
@gilbarbara any update on this? I'm working on mobile now and running out of space!

Although as it is, your player works great as a 'slide in from the top/bottom of the screen' dealio with React Spring 👍

**Comment by robksawyer** [comment]
Loving the module! It's looking great.

**Comment by gilbarbara** [comment]
Implemented in 0.12.0 🎉
