### ISSUE TITLE
Changing the "play" props restarts track rather than resume

### ISSUE THREAD

**Issue by Jaja0624** [gilbarbara/react-spotify-web-playback#43]
If we only change "isPlaying" prop to true the track will restart. Possible to resume?

Cheers

**Comment by gilbarbara** [comment]
Not sure what you mean as there's no `isPlaying` prop.

**Comment by Jaja0624** [comment]
sorry i meant from the callback state object (when the player updates).

**Comment by gilbarbara** [comment]
So, your original title was correct...

I'd assume that you meant to change the behavior of the "play" prop to resume playing if a track is already loaded?
