### ISSUE TITLE
Error when trying to play URI in Create-React-App Typescript project

### ISSUE THREAD

**Issue by AttilaTheFun** [gilbarbara/react-spotify-web-playback#46]
I wanted to test out this package so I created a fresh typescript project with Create React App and installed this package with "npm install --save react-spotify-web-playback".

Then I edited the App component to include the Spotify player:
```
import React from 'react';
import SpotifyPlayer from 'react-spotify-web-playback';
import './App.css';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <SpotifyPlayer
  token="MY_TOKEN"
  uris={['spotify:artist:6HQYnRM4OzToCYPpVBInuU']}
/>
      </header>
    </div>
  );
}

export default App;
```

When I run this, the player shows up but I get the following error when trying to play:
```
Spotify Web Player: undefined is not an object (evaluating 'player.device.volume_percent')
```
In Chrome I get this stack trace:
<img width="1030" alt="Screen Shot 2020-12-11 at 4 04 24 AM" src="https://user-images.githubusercontent.com/3255391/101901540-0a461480-3b66-11eb-9b50-4d4c2b7449ce.png">

Any ideas?

**Comment by gilbarbara** [comment]
hey @AttilaTheFun 

No idea. I just create a codesandbox with the same code you posted and it's working properly.
https://codesandbox.io/s/spotifyplayer-nn6no

Does your token have all the required scopes?
Can you try to get a new one with this [link](https://accounts.spotify.com/en/authorize?response_type=token&client_id=adaaf209fb064dfab873a71817029e0d&redirect_uri=https:%2F%2Fdeveloper.spotify.com%2Fdocumentation%2Fweb-playback-sdk%2Fquick-start%2F&scope=streaming%20user-read-email%20user-read-private%20user-library-read%20user-library-modify%20user-read-playback-state%20user-modify-playback-state&show_dialog=true)?

**Comment by AttilaTheFun** [comment]
Hmm so that seemed to work, but it wouldn't let me play the song from the browser window. It forced me to pick a device and play from that Spotify client instead. Is it not possible to play from the browser itself?

**Comment by gilbarbara** [comment]
Hello!

What did work? The sandbox or the token?

Yes, it's expected for it to create a player and use it on the desktop.
Mobile browsers aren't supported by the SDK.

**Comment by AttilaTheFun** [comment]
I was able to play from one of my existing Spotify devices using the player. The web playback SDK docs demonstrates creating a player in a browser which you can then play from as a target device. I was wondering if this library would allow for playback inside the browser tab itself by creating a new device and then playing from it, or if it can just act as a "remote control" for other devices.

**Comment by gilbarbara** [comment]
hey @AttilaTheFun 

Yes, definitely. It's the whole point of this package.
Did you check the demo in a **supported desktop browser**? 

<img width="563" alt="supported-browsers" src="https://user-images.githubusercontent.com/31954/102289216-de87ad80-3f1c-11eb-9bb1-04e56c3e65fc.png">

You can read about it in the official [docs](https://developer.spotify.com/documentation/web-playback-sdk).

**Comment by AttilaTheFun** [comment]
@gilbarbara thanks! I think I might have tried to use it in Safari before. Both the demo and the typescript react app finally worked for me in Chrome.
