### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by 1mm0rt4l1t9** [gilbarbara/react-spotify-web-playback#47]
Yo! I created new project with create-react-app n only one thing I do install react spotify web playback, but I got TypeError: Cannot read property 'length' of undefined after component rendered. 
![Untitled](https://user-images.githubusercontent.com/67856658/103479685-753ee000-4de0-11eb-922f-d980f9df43f5.png)

**Comment by EuanMorgan** [comment]
Hello, I'm having the same issue, did you find a fix for this?
