### ISSUE TITLE
Initial autoplay does not work

### ISSUE THREAD

**Issue by mlam28** [gilbarbara/react-spotify-web-playback#5]
Hi, 

The first time a song is loaded into the player's uris prop, the player does not automatically play despite giving it the prop autoplay={true}.  The web player will only play if you click the play button located on the web player.

In addition, when only one track uri specifically is on the first load of a uri into the player, playback does not work at all. 

Are there any suggestions for these issues? 

Thanks,
Michelle

**Comment by mlam28** [comment]
After further debugging it seems that autoPlay={true} does not work at all. Can you please fix this issue? 

Thanks,
Michelle

**Comment by gilbarbara** [comment]
Hey,
The autoPlay is being used in the demo and it works.
