### ISSUE TITLE
Error 403 trying to play the song

### ISSUE THREAD

**Issue by didacus** [gilbarbara/react-spotify-web-playback#50]
I am getting a 403 error. Has anyone come across this? I searched the web, and it seems to be something about the account be disabled. However, my account is fully functional. When I click on the console, it says no token provided, but I added that to the player. Any ideas what might be causing this?

**Comment by gilbarbara** [comment]
hey @didacus 
It's impossible to know what's happening without an example.
Please post a codesandbox.

**Comment by breiko83** [comment]
Does this player require Shopify Premium account?

I'm playing around with their Player API and their documentation says:
`If the user making the request is non-premium, a 403 FORBIDDEN response code will be returned.`

**Comment by gilbarbara** [comment]
Yes. This component is just a wrapper on top of the Spotify Web Player SDK. Please refer to their [documentation](https://developer.spotify.com/documentation/web-playback-sdk/).
