### ISSUE TITLE
Bump to React 17

### ISSUE THREAD

**Issue by fheisler** [gilbarbara/react-spotify-web-playback#53]
Thanks for the fantastic package!

It would be great to upgrade dependencies and peer dependencies to the latest `17.0.1` React and react-dom.

**Comment by jccdev45** [comment]
I figured out a temporary solution until an update is rolled out:
- Fork & clone the repo then run `npm i` in your local copy.
- Run either `npm i react@17.0.0 react-dom@17.0.0` or `npm i react@latest react-dom@latest`
- Run `npm run build`. Remove "lib" from .gitignore.
- Add, commit & push your changes to Github. You may encounter an error when trying to commit, I solved this with `rm -rf ~/.nvm` and then reinstalling the latest versions of nvm & node.
- Run `npm i https://www.github.com/<username>/<name-of-cloned-repo>`. Your package.json should read under dependencies: "react-spotify-web-playback": "github:<username>/react-spotify-web-playback"

I was only using this package in a code-along minimal Spotify clone project so I have a very small use-case but I didn't have any issues after these steps. I'll be continuing to tinker and mess with it on my own from here so if I do run into any problems, I will report back. Hope this helps.

**Comment by fheisler** [comment]
@jccdev45 thanks for the notes! I did something similar on a [fork](https://github.com/fheisler/react-spotify-web-playback/commits/built) for now. (If anyone wants to use or copy that directly, note that the "built" branch also includes some other custom code after the version bump.)

**Comment by jccdev45** [comment]
Ah good stuff, two steps ahead. Nice work 👏

**Comment by gilbarbara** [comment]
Just install it with `npm i --legacy-peer-deps`

**Comment by gilbarbara** [comment]
Updated in 0.8.2
