### ISSUE TITLE
Change device display name?

### ISSUE THREAD

**Issue by alexroumi** [gilbarbara/react-spotify-web-playback#55]
Is it possible to change the "device" display name of the player?

**Comment by gilbarbara** [comment]
hey @alexroumi 

Did you try to change the `name` prop?

**Comment by alexroumi** [comment]
Still the same

```react
<SpotifyPlayer
      token={accessToken}
      showSaveIcon
      callback={(state) => {
        if (!state.isPlaying) setPlay(false);
      }}
      play={play}
      uris={trackUri ? [trackUri] : []}
      name="Simplify"
    />
```

**Comment by gilbarbara** [comment]
Humm, not sure I understand the problem then.

Which name do you see? Where?

**Comment by alexroumi** [comment]
How do I change that:

![image](https://user-images.githubusercontent.com/59561790/111998851-18241200-8b25-11eb-91a2-f1a2b7be97ed.png)
![image](https://user-images.githubusercontent.com/59561790/111998886-207c4d00-8b25-11eb-8b3b-e63172bd49a8.png)

**Comment by alexroumi** [comment]
never mind  fixed it. It was the position of the property that caused the problem
