### ISSUE TITLE
Issue playing songs

### ISSUE THREAD

**Issue by JacobwBruce** [gilbarbara/react-spotify-web-playback#57]
I have an issue playing a song from the uris prop, when I connect to a device to play from, it just starts playing whatever I was previously listening to and does not start playing whatever was passed into the component. I also get an error in the Spotify app saying 'Can't play the current song'. I've been debugging for a couple of days now and I can't tell if this is a bug from here or in my code...
My code looks like this:
```
<SpotifyPlayer
    token={user.accessToken}
    uris={['spotify:track:5BvGdjGZKbsrtfA05Yg23W']}
    name='TestingPlayer'
    showSaveIcon={true}
    magnifySliderOnHover={true}
    styles={{
        activeColor: '#4b5dfc',
        sliderColor: '#4b5dfc',
        sliderHandleColor: '#4b5dfc',
    }}
/>
```

**Comment by gilbarbara** [comment]
hey @JacobwBruce 

I don't know what you mean by "when I connect to a device to play from..."
Can you create a codesandbox with a minimal reproducible example?

**Comment by jmyshadow** [comment]
Have you tried passing the prop syncExternalDevice={false} ?

**Comment by JacobwBruce** [comment]
Came back to this today and its working all of a sudden, I've made no changes or anything and it suddenly works lol. I guess this issue can be closed.
