### ISSUE TITLE
issue in playing the song

### ISSUE THREAD

**Issue by shivamkcodes** [gilbarbara/react-spotify-web-playback#59]
when i want to use the player it gives me the 401 error..even when i go its official npm page nd try to run the payer on view demo.it returns the same error when i provide my accesstoken..

this is route which is not able to get fetched   https://api.spotify.com/v1/melody/v1/check_scope?scope=web-playback 401

![Screenshot (10)](https://user-images.githubusercontent.com/58622797/112518634-8d127880-8dbf-11eb-90cd-9c49fa35c9a4.png)

**Comment by gilbarbara** [comment]
This is not a [problem](https://httpstatuses.com/401) with this library...
You need a premium Spotify account to use their Playback SDK.

**Comment by arjnai21** [comment]
I had the same issue and I do have a premium spotify account.
