### ISSUE TITLE
403 error premium only device

### ISSUE THREAD

**Issue by ranahiren27** [gilbarbara/react-spotify-web-playback#60]
I'm not able to use player it's giving following error
{"error_type":"INVALID_LICENSE","message":"Device registration is not allowed: premium_only_device","error_code":9}

**Comment by gilbarbara** [comment]
This library is just a wrapper on top of the Spotify SDK/API so I can't help with requests/responses.
Check the [docs](https://developer.spotify.com/documentation/web-playback-sdk/) to make sure you meet their requirements.
