### ISSUE TITLE
Player crashes in Android Chrome

### ISSUE THREAD

**Issue by luisfuertes** [gilbarbara/react-spotify-web-playback#62]
**Describe the bug**
When try to load a web with player, player crash.

This request failed
PUT https://api.spotify.com/v1/me/player/play?device_id=

I think in mobile cant get de device_id because it send empty

**To Reproduce**
1. Open player in Chrome on Android

**Expected behavior**
Load player like Chrome on desktop

**Comment by gilbarbara** [comment]
Hey @luisfuertes 

Android isn't supported by the [Web Playback SDK](https://developer.spotify.com/documentation/web-playback-sdk/).

The player should load and show the external devices, anyway.
If that isn't happening, please create a minimal codesandbox reproduction.
