### ISSUE TITLE
Firefox CORS Error

### ISSUE THREAD

**Issue by Hephaestos** [gilbarbara/react-spotify-web-playback#63]
**Describe the bug**
Playback is being blocked by a Cross Origin Request Blocked error on Firefox. This is happening both in my use of the component as well as on your demo

**To Reproduce**
Open your demo https://react-spotify-web-playback.gilbarbara.dev/
Open the developer console

**Screenshots**
![image](https://user-images.githubusercontent.com/8532135/115786168-734c5d00-a38e-11eb-81be-5d8c3d283a14.png)
![image](https://user-images.githubusercontent.com/8532135/115786199-7c3d2e80-a38e-11eb-835e-158330c5d694.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 87.0

**Comment by gilbarbara** [comment]
Just tested in Firefox 87 and 88 on a Mac and I didn't have any errors.

**Comment by gilbarbara** [comment]
The last line in your print mentions a moz-extension. 
Try to disable all extensions.

**Comment by Hephaestos** [comment]
Sure enough it was being caused by Privacy Badger. Thank you
