### ISSUE TITLE
Web playback with podcast episodes.

### ISSUE THREAD

**Issue by claypark-dev** [gilbarbara/react-spotify-web-playback#65]
Not so much a bug, just wanted to drop this in here, the spotify api now can call to podcast episodes which are oddly enough different than shows. It would be nice to be able to populate the player with an episode. It looks like just updating the valid types in validate URI should be enough to solve the problem.

**Comment by gilbarbara** [comment]
hey @claypark-dev 
Sorry for the long delay!

I'm trying to play an episode URI but it gave me a 400 error with **Non supported context uri**
Is it working for you?
