### ISSUE TITLE
deepmerge is not a function (on RangeSlider)

### ISSUE THREAD

**Issue by VituBR19** [gilbarbara/react-spotify-web-playback#67]
**Bug**
When the component is loaded, it just shows the error
![image](https://user-images.githubusercontent.com/59032828/127225486-7d928a30-379e-4a70-b33e-9cc7cef34e12.png)

**My Usage**
Using component like: 
``{running && (
                        <SpotifyPlayer token={authorize} uris={[running]} />
                    )}``
                    
My scopes:
``var scopes =
    'streaming user-read-email user-read-private user-library-read user-library-modify user-read-playback-state user-modify-playback-state';``
    
React version : 17.0.0

**Comment by gilbarbara** [comment]
@VituBR19
Please post a codesandbox reproducing the error.

**Comment by VituBR19** [comment]
@gilbarbara Hello, I'm studying Vite, so you can run the project like `yarn vite` after install dependencies. Have to include your client id and client secret on app.tsx and auth.ts

here it is:
https://codesandbox.io/s/awesome-poitras-61zb1?file=/src/services/auth.ts

**Comment by gilbarbara** [comment]
Most likely is a problem with Vite since this library works with webpack...

**Comment by VituBR19** [comment]
hmmm. I didn't know that

thanks for the observation

**Comment by gilbarbara** [comment]
Check if the deepmerge dependency is installed in the node_modules and if vite is bundling it.
Also, search for issues in both vite and deepmerge repos.

**Comment by RubyBrewsday** [comment]
@gilbarbara Hi there, so I'm running into a similar issue but with ESbuild instead of webpack. Did you happen to know of anyone else who ran into this issue or have some advice on possibly a fix?
