### ISSUE TITLE
Invalid Token Scopes

### ISSUE THREAD

**Issue by kawern** [gilbarbara/react-spotify-web-playback#71]
Hello. I'm using a token generation with an authorization flow, which works fine with fetching the data etc.

But when I'm trying to pass the same token in this script, i get a Spotify Web Player: Invalid token scopes. error in the webplayer.

It works fine if I create a token on spotifys "quick guide", and even when removing "Bearer " from my token (.replace("Bearer ", "")), it still gives me the Spotify Web Player: Invalid token scopes. error.

I know you usually request a sandbox enviroment to see it for yourself (in other issues/help requests), but I can't make a sandbox that works.

Scopes:
streaming
user-read-email
user-read-private
user-read-playback-state
user-read-currently-playing
user-library-read
playlist-read-private
playlist-read-collaborative
user-modify-playback-state

Player:
`<SpotifyWebPlayer
  token={token}
  uris={[
    `spotify:track:${id}`
]}
  autoPlay={true}
  styles={{
    activeColor: '#000',
    bgColor: '#fff',
    color: '#000',
    loaderColor: '#EE0979',
    sliderColor: '#1cb954',
    trackArtistColor: '#000',
    trackNameColor: '#000',
  }}
/>`

**Comment by gilbarbara** [comment]
hey @kawern 

> It works fine if I create a token on Spotify "quick guide", and even when removing "Bearer " from my token (.replace("Bearer ", "")), it still gives me the Spotify Web Player: Invalid token scopes. error.

Does it work that way or not?

Anyway, the demo and some other projects that use this player are working, so it's not a problem with the library itself.

**Comment by kawern** [comment]
It works with the token you generate that works for one our, but it doesn't work with my authorization flow. It says Invalid Token Scopes, and i was just wondering if you had any idea why :)!

Thanks for the reply!

**Comment by gilbarbara** [comment]
hey @kawern
This player is just a UI to control the Web Playback SDK and send some requests to the API.

You can try calling some of the endpoints this library uses with your token and see if it works directly.
