### ISSUE TITLE
Spotify Web Player: Invalid token scopes.

### ISSUE THREAD

**Issue by joshua-isaac** [gilbarbara/react-spotify-web-playback#73]
**Describe the bug**
Im trying to use this package with Next.js, however i keep running into this error: "Spotify Web Player: Invalid token scopes."

<img width="633" alt="Screen Shot 2021-09-26 at 2 23 13 PM" src="https://user-images.githubusercontent.com/40035381/134819628-57114e56-abf3-4fed-b35c-2cf0a48943ca.png">

```
{
  "error": {
      "status": 401,
      "message": "No token provided"
  }
}
```

I'm using next-auth to authenticate and get the token from users:

```
import NextAuth from "next-auth";
import SpotifyProvider from "next-auth/providers/spotify";

export default NextAuth({
  // Configure one or more authentication providers
  providers: [
    SpotifyProvider({
      clientId: "my-client-id",
      clientSecret: "my-client-secret",
      scope:
        "streaming user-read-email user-read-private user-read-playback-state user-modify-playback-state",
    }),
  ],
  callbacks: {
    async jwt({ token, account }) {
      // Persist the OAuth access_token to the token right after signin
      if (account) {
        token.accessToken = account.access_token;
      }
      return token;
    },
    async session({ session, token, user }) {
      // Send properties to the client, like an access_token from a provider.
      session.accessToken = token.accessToken;
      return session;
    },
  },
});
```

Im trying to use the package in my Index.js file like so:

```
import SpotifyPlayer from "react-spotify-web-playback";
import { useSession } from "next-auth/react";

export default function Home() {
  const { data: session, status } = useSession();

  if (status === "unauthenticated") {
    return (
      <div>
        <Link href="/api/auth/signin">
          <a>Sign In</a>
        </Link>
      </div>
    );
  }

  if (status === "loading") {
    return (
      <div>
        <p>Loading...</p>
      </div>
    );
  }

  return (
    <div>
      <h1>Party Time</h1>
      <SpotifyPlayer token={session.accessToken} />
    </div>
  );
}
```

I can confirm i am able to access the access token on the client using the useSession hook, however when i pass ` token={session.accessToken}` into the `<SpotifyPlayer />`, i keep getting this error.

Any ideas?

Thanks!

**Comment by vettorazi** [comment]
@gilbarbara is correct (obviously). you need to use the package with SSR.
But even, the AccessToken I receive from NextAuth isn't working.
I keep receiving this error:

![Screenshot 2023-02-15 at 2 47 09 PM](https://user-images.githubusercontent.com/7634575/219205948-85992276-c3d6-4427-966d-39b427ac1a0d.png)
![Screenshot 2023-02-15 at 2 47 21 PM](https://user-images.githubusercontent.com/7634575/219205987-ce824fc6-7279-4bd5-8827-825bf25e1ae2.png)


@gilbarbara por favor me ajuda :'( haha

**Comment by gilbarbara** [comment]
Hey @vettorazi 

From what I understand from the Next-Auth docs, it is doing a [Client Credentials Flow](https://developer.spotify.com/documentation/general/guides/authorization/client-credentials/), and returns an "app" access_token. This token allows you to perform **unscoped** server requests: get global data, swap authorization code, refresh tokens, and such.

This player require an user token using the [Authorization Code Flow](https://developer.spotify.com/documentation/general/guides/authorization/code-flow/).

The user must explicitly authorize your app to request the scoped data. So, the user clicks on a link that opens a Spotify page where the user can approve the app.
Link format: **https://accounts.spotify.com/authorize?client_id=YOUR_CLIENT_ID&response_type=code&redirect_uri=YOUR_REDIRECT_URL&scope=user-read-email%20user-library-read%20user-library-modify%20user-top-read%20user-read-playback-state%20playlist-modify-public%20playlist-modify-private%20streaming%20user-read-birthdate%20user-read-email%20user-read-private%20user-modify-playback-state&state=auth**

If the user authorizes the access, it redirects the user to your app with a `code` and `state` query parameters.
Using your app token, you can swap this "code" to a user access_token and refresh_token, like this:

```ts
async function getToken(code: string) {
  return fetch('https://accounts.spotify.com/api/token', {
    method: 'POST',
    headers: {
      Authorization: `Basic ${btoa(`${clientId}:${clientSecret}`)}`,
    },
    body: new URLSearchParams({
      grant_type: 'authorization_code',
      code,
      redirect_uri: 'http://localhost:3000',
    }),
  }).then(response => response.json());
}
```

Did it help?

**Comment by gilbarbara** [comment]
Btw, user tokens start with **B**

**Comment by vettorazi** [comment]
Thank you so much for your help @gilbarbara it helped a lot!
I got the player working on my application, but isn't super consistent, which makes me wonder what I'm doing wrong.
Sometimes it works first try, some just don't, and some it works but it throws some errors in the console, like this:
Any idea on why this is happening?
(When the page, with the accesstoken reloads, I see the log with the accesstoken, then after 30 seconds or so, the player loads, or don't, image below)
![Screenshot 2023-02-15 at 10 46 00 PM](https://user-images.githubusercontent.com/7634575/219289358-e0ca2704-0651-4516-b7c8-b0de703cb2d4.png)
