### ISSUE TITLE
Uri with type 'episode' not playing: "Invalid URI"

### ISSUE THREAD

**Issue by paulhuisman** [gilbarbara/react-spotify-web-playback#87]
**Describe the bug**
Via the Spotify api I can fetch my shows' episodes via the "getShowEpisodes" endpoint (see https://developer.spotify.com/console/get-show-episodes/).

However when I want to play them via your player i get an error that the uri type (episode) is not allowed. Is there a specific reason for this? I can make a PR.

**Version used**
0.9.1 (with React 17.0.2)

**Comment by gilbarbara** [comment]
hey @paulhuisman 

This was already discussed in #65.
The API doesn't support episode uris

**Comment by paulhuisman** [comment]
Why won't they support that..  :( 

Thanks for your reply.
