### ISSUE TITLE
Adding 'currently playing on' functionality

### ISSUE THREAD

**Issue by jdstregz** [gilbarbara/react-spotify-web-playback#9]
I was thinking it would be cool to add a currently playing on functionality to the player.

Currently if you load a player with no URIs, it doesn't indicate that the music is player on another device (along with the song). Usually if you load up spotify on your phone or desktop and the music is playing on the other device, it will tell you. Pressing play would result in automatically switching playback to that current device. 

It looks like this player already performs that if you select on devices and select the web player. Would just implement that for pressing play on a player that has no URIs

**Comment by gilbarbara** [comment]
hey @jdstregz,

I've added a prop for that: `syncExternalDevice`. It will be available in 0.7.0.

Here's the list of changes: https://github.com/gilbarbara/react-spotify-web-playback/pull/20 for this version.
I still have some UIs updates to finish before I publish it but it shouldn't tell take long.

**Comment by gilbarbara** [comment]
Added in 0.7.0
