### ISSUE TITLE
The volume drop-up is now a drop-down and it is being by the screen.

### ISSUE THREAD

**Issue by o-laj** [gilbarbara/react-spotify-web-playback#90]
The "volume" and "connected devices"  drop-up is now a drop-down and it is being covered by the screen.

**Comment by gilbarbara** [comment]
hey @o-laj 

As stated in the new issue template:

> **Codesandbox link (Required)**
> Include a codesandbox will help us to investigate the issue quicker.

Does it work in the [demo](https://react-spotify-web-playback.gilbarbara.dev/)?

**Comment by givensuman** [comment]
I'm running into this as well. Volume is seemingly missing.
It does not seem to work in the demo. My token does have the 'user-modify-playback-state', and there are no errors in console.

Demo:
![screencap](https://user-images.githubusercontent.com/16063606/152696812-4fb5323c-0a93-4b3e-803b-e47c8641dd1d.PNG)

Implementation in my app:
![screencap2](https://user-images.githubusercontent.com/16063606/152696813-5659ba5b-5e02-42ad-985d-adaacb69b886.PNG)

For what it's worth, here's the component that implements it:

```js
import React from 'react'
import SpotifyPlayer from 'react-spotify-web-playback'
import styled from '@emotion/styled'

import usePlayerControls from '../hooks/usePlayerControls'

const Wrapper = styled.div`
    position: absolute;
    bottom: 0;
    width: 100%;
`

const Player = ({ token }) => {

    const { player } = usePlayerControls()

    return (
        <Wrapper>
            <SpotifyPlayer
            autoPlay
            persistDeviceSelection
            showSaveIcon
            name='Web Player'
            token={token}
            uris={player.uris}
            play={player.playState}
            />
        </Wrapper>
    )
}

export default Player
```

**Comment by gilbarbara** [comment]
hey @givensuman 
This issue was about positioning, not the button being hidden in small screens.

Anyway, the Volume button disappears on small screens since devices of these sizes have dedicated hardware buttons.
But this could be improved for sure. Feel free to open a PR.
