### ISSUE TITLE
When "uris" prop changes the new track does not play automatically, even with the prop: "autoPlay" set to true

### ISSUE THREAD

**Issue by rohhenry** [gilbarbara/react-spotify-web-playback#91]
First, thank you for creating this player it saved me a lot of headache. However there seems to be a bug with the SpotifyPlayer component detecting uri changes.

**Describe the bug**
`[trackURI, setTrackURI] = useState('')`
I have been trying to get the track to play another track only when it ends.

When a track ends, the s.progressMs goes to 0, the s.type is a "player_update", and the s.isPlaying is false.
So for the callback prop in the player I have:

```
(s) => {
          console.log(s);
          if (
            s.progressMs === 0 &&
            s.type === "player_update" &&
            s.isPlaying === false
          ) {
            backend
              .update(trackURI, 1)
              .then((newTrackURI) =>
                setTrackURI(newTrackURI)
              );
          }
```

I expected the player to change tracks with the newTrackURI, and then to play automatically.
However when a track ends this does not happen.
The call back does not even get called until the user clicks play which then sends an update to update the track and play it. 

My solution was to manually mount / remount the entire SpotifyPlayer component by setting its prop `key={trackURI}`, however, this is not very visually appealing and is slow.

**Comment by gilbarbara** [comment]
hey @rohhenry 

The `autoPlay` only works for the first time the component mounts and after that, it won't have any effect.
You can use the `play` prop to control the internal state as it used in the [demo](https://github.com/gilbarbara/react-spotify-web-playback/blob/main/demo/src/App.tsx#L83)
