### ISSUE TITLE
Play issue on changedURIs

### ISSUE THREAD

**Issue by sbereghici** [gilbarbara/react-spotify-web-playback#97]
**Describe the bug**
If you pause the current playing song, then change the uris, the player continues to play the previous song, not the expected one

**To Reproduce**
1. Go to your demo
2. Click on 'Play an artist'
3. Click on 'Pause' from player
4. Click on 'Play an album'

**Expected behavior**
The song you expect to play, will not play

**Additional context**
The quick fix will be to remove the isPlaying clause from index.tsx:188
 const shouldPlay = (changedURIs && isPlaying) || !!(isReady && (autoPlay || playProp)); -> 
 const shouldPlay = changedURIs || !!(isReady && (autoPlay || playProp));

**Comment by gilbarbara** [comment]
hey @sbereghici 

I couldn't reproduce this behavior with the above steps.

![2022-01-31 09 42 49](https://user-images.githubusercontent.com/31954/151796418-d86a79fd-9ca3-4890-bdc2-2dc15dbca0a0.gif)

**Comment by sbereghici** [comment]
Well, pretty strange ... 
![CPT2201311547-760x348](https://user-images.githubusercontent.com/15802507/151805112-d467e843-5608-4aee-9c50-901b72b4f556.gif)

**Comment by gilbarbara** [comment]
Which browser and version? 
Can you test in an incognito window to make sure it's not some interference from extensions and/or scripts?

**Comment by sbereghici** [comment]
> Which browser and version? Can you test in an incognito window to make sure it's not some interference from extensions and/or scripts?

Chrome v97.0.4692.99 ... I've tried in incognito and it works the same way, playing the old song, also tried with Edge, same result.

**Comment by gilbarbara** [comment]
Are you using this [url](https://react-spotify-web-playback.gilbarbara.dev/) or the demo inside the codesandbox?
The Web Playback SDK has some issues with iframes

**Comment by sbereghici** [comment]
> Are you using this [url](https://react-spotify-web-playback.gilbarbara.dev/) or the demo inside the codesandbox? The Web Playback SDK has some issues with iframes

Hey @gilbarbara, I'm using the [url](https://react-spotify-web-playback.gilbarbara.dev/).

**Comment by gilbarbara** [comment]
Couldn't replicate this behavior.
